version: "3"

services:
  db:
    image: postgres:14.1-alpine
    hostname: dbpokemon
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=pokemon_database
    ports:
      - '5432:5432'
    volumes: 
      - ./database/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - dbapp:/var/lib/postgresql/data
      
networks:
  app:
    driver: bridge

volumes:
  dbapp:
    driver: local